CC=		gcc
CFLAGS=		-Wall -g -std=gnu99
LD=		gcc
LDFLAGS=	-L. 
TARGETS=	program

all:		$(TARGETS)

program:	main.o library.o
	$(LD) $(LDFLAGS) -o $@ $^

%.o:		%.c
	$(CC) $(CFLAGS) -c -o $@ $^

clean:
	rm -f $(TARGETS) *.o
